/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'alertType' : string,
  'messageTamil' : string,
  'targetLat' : number,
  'targetLng' : number,
  'messageEnglish' : string,
  'radiusKm' : number,
}
export interface Incident {
  'id' : bigint,
  'status' : Status,
  'latitude' : number,
  'description' : string,
  'longitude' : number,
  'village' : string,
  'severity' : Severity,
  'incidentType' : string,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface Stats {
  'volunteersByStatus' : {
    'deployed' : bigint,
    'available' : bigint,
    'unavailable' : bigint,
  },
  'incidentsBySeverity' : {
    'low' : bigint,
    'high' : bigint,
    'critical' : bigint,
    'medium' : bigint,
  },
}
export type Status = { 'resolved' : null } |
  { 'active' : null } |
  { 'reported' : null };
export interface UserProfile {
  'name' : string,
  'village' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : bigint,
  'status' : VolunteerStatus,
  'name' : string,
  'village' : string,
  'phone' : string,
  'skills' : string,
}
export type VolunteerStatus = { 'deployed' : null } |
  { 'available' : null } |
  { 'unavailable' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<
    [string, string, number, number, number, string],
    bigint
  >,
  'createIncident' : ActorMethod<
    [string, number, number, Severity, string, string],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAlerts' : ActorMethod<[], Array<Alert>>,
  'listIncidents' : ActorMethod<[], Array<Incident>>,
  'listVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'registerVolunteer' : ActorMethod<[string, string, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIncidentStatus' : ActorMethod<[bigint, Status], undefined>,
  'updateVolunteerStatus' : ActorMethod<[bigint, VolunteerStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];