/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'village' : IDL.Text,
  'phone' : IDL.Text,
});
export const Stats = IDL.Record({
  'volunteersByStatus' : IDL.Record({
    'deployed' : IDL.Nat,
    'available' : IDL.Nat,
    'unavailable' : IDL.Nat,
  }),
  'incidentsBySeverity' : IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'critical' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'messageTamil' : IDL.Text,
  'targetLat' : IDL.Float64,
  'targetLng' : IDL.Float64,
  'messageEnglish' : IDL.Text,
  'radiusKm' : IDL.Float64,
});
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'reported' : IDL.Null,
});
export const Incident = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'latitude' : IDL.Float64,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'village' : IDL.Text,
  'severity' : Severity,
  'incidentType' : IDL.Text,
});
export const VolunteerStatus = IDL.Variant({
  'deployed' : IDL.Null,
  'available' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const Volunteer = IDL.Record({
  'id' : IDL.Nat,
  'status' : VolunteerStatus,
  'name' : IDL.Text,
  'village' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createIncident' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, Severity, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'listIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'listVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIncidentStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateVolunteerStatus' : IDL.Func([IDL.Nat, VolunteerStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'village' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'volunteersByStatus' : IDL.Record({
      'deployed' : IDL.Nat,
      'available' : IDL.Nat,
      'unavailable' : IDL.Nat,
    }),
    'incidentsBySeverity' : IDL.Record({
      'low' : IDL.Nat,
      'high' : IDL.Nat,
      'critical' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'messageTamil' : IDL.Text,
    'targetLat' : IDL.Float64,
    'targetLng' : IDL.Float64,
    'messageEnglish' : IDL.Text,
    'radiusKm' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'reported' : IDL.Null,
  });
  const Incident = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'latitude' : IDL.Float64,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'village' : IDL.Text,
    'severity' : Severity,
    'incidentType' : IDL.Text,
  });
  const VolunteerStatus = IDL.Variant({
    'deployed' : IDL.Null,
    'available' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const Volunteer = IDL.Record({
    'id' : IDL.Nat,
    'status' : VolunteerStatus,
    'name' : IDL.Text,
    'village' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createIncident' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, Severity, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'listIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'listVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIncidentStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateVolunteerStatus' : IDL.Func([IDL.Nat, VolunteerStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };